# encoding: utf-8
# --------------------------------#
# 提供一些基本的算法
# --------------------------------#

# 计算时间列表中最大值,平均值和最小值
# 计算平均值/最大登录时间等信息
# rs : 线程池对象返回列表值
# name : 测试操作名
def printResult(rs,name):
    total_time = 0
    max_time = 0

    print('----------------------------------------------------------')
    for i in rs:
        print(i.get())
        total_time+= i.get()
        if i.get() > max_time:
            max_time = i.get()
    print('----------------------------------------------------------')
    print('平均%s时间为:%0.3f'%(name,total_time/len(rs)))
    print('最大%s时间为:%0.3f'%(name,max_time))
    # print('平均登出转发状态时间为:%0.3f' % (total_logout / len(rs)))
    # print('最大登出时间为:%0.3f'%(max_logout_time))
    print('----------------------------------------------------------')


# 通过序号获取医生姓名
def getDocName(Id):
    return getDocList()[Id][0]

# 定义医生列表信息
def getDocList():
    ret1 = (
        ('ajx',), ('anhong',), ('aosong',), ('baidong',), ('baihongbo',), ('bailinguo',), ('baixuepeng',), ('baiyu',),
        ('baiyunyiyuan',), ('baoshihai',), ('baoyanping',), ('blwangli',), ('blzb',), ('bywanghong',), ('caibangzhen',),
        ('caiqihua',), ('caiqingyong',), ('caixiaolin',), ('caiyiling',), ('caizufeng',), ('caoailing',), ('caobilan',),
        ('caoguojing',), ('caojinquan',), ('caokai',), ('caoming',), ('caomingyan',), ('caoshengrui',),
        ('caoshengrui2',),
        ('caoxian',), ('caoxueqiu',), ('caoyu',), ('changchun',), ('changchun4',), ('changjianguo',), ('chaodingding',),
        ('chaodingding4',), ('chenchang',), ('chenchang4',), ('chenderong',), ('chengfumei',), ('chenghelong',),
        ('chenguangfen',), ('chenguanzheng',), ('chengxianbing',), ('chengxiaoming',), ('chengyimin',),
        ('chengyingjie',),
        ('chengyu',), ('chenhailan',), ('chenhaiwen',), ('chenhong',), ('chenhong1',), ('chenhong4',), ('chenhongli',),
        ('chenhongzhen',), ('chenhui',), ('chenhuixiu',), ('chenhuixiu2',), ('chenhuiyun',), ('chenjian2',),
        ('chenjing3',),
        ('chenjuan2',), ('chenke',), ('chenli',), ('chenlihua',), ('chenlin1',), ('chenmiao',), ('chenming',),
        ('chenning',), ('chenqiong',), ('chenqiyu',), ('chenruibo',), ('chenshaojie',), ('chenshijun2',),
        ('chensongbo',),
        ('chentao',), ('chenwei',), ('chenwei2',), ('chenweirong',), ('chenweirong4',), ('chenwenfei',),
        ('chenxianru',),
        ('chenxiaodong',), ('chenxiaohui',), ('chenxing',), ('chenxionggao',), ('chenxu',), ('chenxuemei',),
        ('chenxuenong',), ('chenyaling',), ('chenyan2',), ('chenyingfu',), ('chenyongtai',), ('chenyongyan',),
        ('chenyuanpin',), ('chenzhihua',), ('cheying',), ('chulan',), ('chuxiuli',), ('cm',), ('congfengfei',),
        ('congfengfei4',), ('cuiguangzhi',), ('cuilong',), ('daihanyun',), ('dailingxian',), ('dailu',), ('dailu4',),
        ('daiweiwei',), ('daiyongfu',), ('danfucheng',), ('dengjunchang',), ('denglijun',), ('dengqingchun',),
        ('dengting',), ('dengweian',), ('dengxiaoxuan',), ('dengxu',), ('dengxu4',), ('dengyunshu',), ('dingguobing',),
        ('dingli2',), ('dingliguang',), ('dingpingsheng',), ('dingzhixin',), ('donghongxia',), ('donghua',),
        ('donghua4',),
        ('dongjiuyan',), ('donglimei',), ('donglongjia',), ('dongshengfeng',), ('dongxian',), ('dongyang',),
        ('dongyifei',),
        ('doulihua',), ('douyan',), ('douyiliang',), ('drtlyg',), ('duanliancheng',), ('ducongrui',), ('duhuiling',),
        ('dujianli',), ('dujun',), ('duqian',), ('duqiyu',), ('duwei1',), ('duxianbao',), ('duxin',), ('duxin2',),
        ('duzhongtao',), ('duzilin',), ('fanghaoran',), ('fangkerui',), ('fangkerui4',), ('fangli',), ('fangwei',),
        ('fangxingguo',), ('fangxuejun',), ('fanhongliang',), ('fanjinmei',), ('fanqinghong',), ('fanxinhua',),
        ('fanyonghui',), ('fanzemin',), ('fanzijian',), ('fengbingmin',), ('fengchao',), ('fenggongqi',), ('fengjun',),
        ('fenglinling',), ('fengshuqin',), ('fengwenxin',), ('fengxiu',), ('fengyan',), ('fengyun',), ('fengyun4',),
        ('fengyuping',), ('fengzhi',), ('fudandan',), ('fuhongyi',), ('fujinyang',), ('fuju4',), ('fujun',),
        ('funengyong',), ('fuxiaoyun',), ('fuxiuzhen',), ('fuyan2',), ('ganlimei',), ('ganlimei4',), ('ganlu1',),
        ('ganlu4',), ('gaobingwen',), ('gaocaixia',), ('gaochongyong',), ('gaodunkuan',), ('gaofen',), ('gaohong',),
        ('gaohongli',), ('gaohongmei2',), ('gaohongwei',), ('gaoming',), ('gaoqin',), ('gaoqin4',), ('gaoshuang',),
        ('gaoxiaohua',), ('gaoxiaoying4',), ('gaoyingbing',), ('gengzhengping',), ('geyanquan',), ('gongjicheng',),
        ('gongjuying',), ('gonglihong',), ('gonglihong2',), ('gongnianchun',), ('gongtiantian',), ('gongxiuzhen',),
        ('gongyuexian',), ('gongyulai',), ('gongzhengpeng',), ('gounengqiang',), ('goushuqiao',), ('gouwenyong',),
        ('guanfeng',), ('guchangshi',), ('gujin',), ('guodaoxin',), ('guoguiying',), ('guohongyuan',), ('guohuaqiang',),
        ('guojian',), ('guolifang',), ('guoqingyan',), ('guoqingyan2',), ('guoqiping',), ('guowenjuan',), ('guoxinna',),
        ('guoyi',), ('guoyong',), ('guoyong4',), ('guqi',), ('guyuanyuan',), ('gxy',), ('gybymjzwsy',), ('gydujun',),
        ('gzchenhong',), ('gzhuangbin',), ('hanchunhong',), ('hanchunhong4',), ('hanpengli',), ('hanpengli2',),
        ('hanwei',),
        ('hanwenzhou',), ('hanxuguang',), ('hanziyu',), ('haobailan',), ('hebing',), ('hedongpo',), ('heguishuang',),
        ('heguojiao',), ('hejiacheng',), ('hejiaojiao',), ('hejiaojiao2',), ('hejing',), ('hejiqiao',), ('helei',),
        ('heliang',), ('hewanyun',), ('hewanyun2',), ('hexia',), ('hexianyong',), ('hexianyong4',), ('hexiuzhen',),
        ('heyangliu',), ('heyangliu4',), ('heyong',), ('hezhou',), ('hjh',), ('hongjiahai4',), ('hongyanping',),
        ('houzhaoyong',), ('houzhaoyong2',), ('houzixiong',), ('huangbinqiang',), ('huangchanghai',),
        ('huangchanghai4',),
        ('huangchunqiao',), ('huangderong',), ('huangjie',), ('huanglihua',), ('huanglihua4',), ('huangmeiying',),
        ('huangmingcai2',), ('huangqingyun',), ('huangrongning',), ('huangweizhen',), ('huangxi',), ('huangxiaoqing',),
        ('huangxiaoqing4',), ('huangxinhua',), ('huangxinhua4',), ('huangyanyan',), ('huangyunhong',),
        ('huangzhaozhi',),
        ('huangzhengyi',), ('huangzhigang',), ('huangzuxiang',), ('huawen',), ('hubingbing',), ('huizhiyi',),
        ('hujie',),
        ('hukang',), ('hulinling',), ('huping',), ('huqiong',), ('husongqin',), ('husuqiu',), ('huwei3',), ('huweili',),
        ('huxuefei',), ('jiabenzhong',), ('jiali',), ('jiangchengwen',), ('jiangcuiping',), ('jiangfengxiao',),
        ('jiangfujun',), ('jiangfuqiu',), ('jiangjinming',), ('jianglilin',), ('jiangqili',), ('jiangqingyuan',),
        ('jiangtaiping',), ('jiangxiaosong',), ('jiangxiaosong4',), ('jiangyinghong',), ('jiangzhengju',),
        ('jiaoanxue',),
        ('jiaofangmin',), ('jiaolimin',), ('jiaowei',), ('jiasufen',), ('jiaxiangqun',), ('jiayonglong',), ('jifeng',),
        ('jinchangjian',), ('jingdacheng',), ('jingdacheng4',), ('jinruhai',), ('jinxiandong',), ('jinxiangxi',),
        ('jinxiaoying',), ('jinzhu',), ('kandongsheng',), ('kanglujing',), ('kangshouzhu',), ('kangxiaoke',),
        ('kangxiaoke4',), ('kezengfang',), ('kezhongquan',), ('kongfanli',), ('konglei',), ('kongling',),
        ('laijingming',),
        ('laijingming4',), ('laikunde',), ('laikunde4',), ('langmingji',), ('lantiangang',), ('lanyi',),
        ('laoshangjuan',),
        ('leihong',), ('leiquansheng',), ('leiyu',), ('leizhihao',), ('leyang',), ('liangchangxing',),
        ('liangchaocheng',),
        ('liangguiping',), ('liangjinfeng',), ('liangli',), ('liangshanshan',), ('lianxin',), ('lianxin4',),
        ('liaode',),
        ('liaojinxiu',), ('liaoxiaoheng',), ('lichaofu',), ('lichuan',), ('lichunhua',), ('lichunhua4',),
        ('lichunmei',),
        ('lidaoyuan',), ('lideming',), ('lideming4',), ('lidingying',), ('lidonghua',), ('lidongying',), ('lifutang',),
        ('ligang',), ('liguohua',), ('liguoping',), ('lihaixiang',), ('lihong4',), ('lihongguang',), ('lihuajun',),
        ('lihui2',), ('lihuiying',), ('liji',), ('lijian',), ('lijianguo',), ('lijianxiong',), ('lijiao',),
        ('lijingcun',),
        ('lijinghai',), ('lijuan',), ('likaiwen3',), ('likaiwen4',), ('lilan',), ('lilinxu',), ('limaolin2',),
        ('limingguo',), ('limingguo4',), ('limingzhu',), ('lina',), ('linan',), ('linbin',), ('linchengli',),
        ('linghuating',), ('linhong',), ('linhuifang',), ('lining',), ('liningyi',), ('linshumei',), ('linwen',),
        ('linwenzhen',), ('linxiaojuan',), ('linxinping',), ('linyuanyuan',), ('linyuanyuan4',), ('linzhenfang',),
        ('liping',), ('liping2',), ('lipingping',), ('lipingyun',), ('liqi',), ('liqianjin',), ('liqiaoyan',),
        ('liqin2',),
        ('liqing2',), ('liqiyang4',), ('liqunhua',), ('lirong2',), ('lirongxing',), ('lishaoan',), ('lishene',),
        ('lishene3',), ('lishene4',), ('lishuxi',), ('lisuwen',), ('litaolang',), ('litianyu',), ('litiehua',),
        ('liting',),
        ('litonghuan',), ('liuaihua',), ('liuaihua4',), ('liuaiping',), ('liubeichen',), ('liucan',), ('liucanqi',),
        ('liucanqi4',), ('liuchuanqiang',), ('liudahu',), ('liudaxing',), ('liudewei',), ('liufang',), ('liufei',),
        ('liufei1',), ('liufuyuan',), ('liuguiying',), ('liuguizhen',), ('liuguomin',), ('liuguomin4',),
        ('liuhengzhao',),
        ('liuhong2',), ('liuhongmei',), ('liuhongmei4',), ('liuhongquan',), ('liuhongtao',), ('liuhuiling',),
        ('liuhuimin',), ('liuhuixia',), ('liuj',), ('liujianchu',), ('liujiang',), ('liujiang4',), ('liujiangbin',),
        ('liujihong',), ('liujing2',), ('liujingliang',), ('liujinxian',), ('liukui',), ('liulaibing',), ('liuli3',),
        ('liulianlian',), ('liulianlian4',), ('liumaolin',), ('liumin2',), ('liumingfu',), ('liumingyang',),
        ('liumorong',),
        ('liuqiong',), ('liuqiuyan',), ('liuqiyang',), ('liuqunying',), ('liushenglian',), ('liusherong',),
        ('liushuanglin',), ('liushuanglin4',), ('liutao4',), ('liutieming',), ('liutonghua',), ('liuwentao',),
        ('liuwupeng',), ('liuwuqi',), ('liuwuqi4',), ('liuxiaofang',), ('liuxiaojun',), ('liuxiaojun4',),
        ('liuxiaoqin4',),
        ('liuxiaorong2',), ('liuxingquan',), ('liuyan',), ('liuyan4',), ('liuyanjun',), ('liuyao',), ('liuyi1',),
        ('liuyin',), ('liuyindan',), ('liuyindan2',), ('liuyong',), ('liuyong4',), ('liuyuanmei',), ('liuyue',),
        ('liuyumei',), ('liuyunchuan',), ('liuyunhua',), ('liuzhannv',), ('liuzhaohui',), ('liuzhen',), ('liuzhen4',),
        ('liuzhengming',), ('liuzhichao',), ('liuzhihui',), ('liuzhiting',), ('liuzhouzhou',), ('liuzhuling',),
        ('liweibai',), ('liweiyi',), ('lixiaofei',), ('lixiaofeng',), ('lixiaogang',), ('lixiaohong',), ('lixin',),
        ('lixinyue',), ('lixun',), ('liyange',), ('liyanping',), ('liyi',), ('liyonggui',), ('liyongwen',),
        ('liyoulin',),
        ('lizeshu',), ('lizhaoxia',), ('lizhengping',), ('lizhihua1',), ('lizhikun',), ('lizhimin',), ('lizhipeng',),
        ('lizhiyu',), ('lizhongqin',), ('lizuolin',), ('lkw',), ('longqifa',), ('longxuanbiao4',), ('longyao',),
        ('longyao4',), ('longyuanbiao',), ('luanlibao',), ('luchangying',), ('luchaowu',), ('ludong',),
        ('luguangliang',),
        ('lujiao',), ('lujiao4',), ('lujing',), ('lumeili',), ('luocaixia',), ('luodefu',), ('luodemin',),
        ('luoganglv',),
        ('luoganglv4',), ('luohongyu',), ('luohuan',), ('luojin',), ('luoliying',), ('luoqian',), ('luoqian2',),
        ('luoqiang',), ('luoqin',), ('luoxiang',), ('luoxue',), ('luoyaling',), ('luoyang',), ('luoyongyou',),
        ('luoyuanping',), ('luoyuanzheng',), ('luozhongyun',), ('lusong',), ('lutianhu',), ('luwanpeng',),
        ('luweijia',),
        ('luxianghua',), ('luxiaodong',), ('luxiaohui',), ('lvpeihong',), ('lvxiaohu',), ('lvxiyang',), ('lwb',),
        ('lxq',),
        ('maaiping',), ('machengqin',), ('madeying',), ('maduanwu',), ('mahong',), ('majianming',), ('majiuai',),
        ('malu',),
        ('maolin',), ('maoshixian',), ('maoxudong',), ('maoyuchen',), ('maqiaoqiao',), ('mawanli',), ('mawenru',),
        ('maxuan',), ('mayan',), ('mayanhong',), ('mayifeng',), ('mayuanhong4',), ('mazefeng',), ('mazhaolei',),
        ('mazhenjun',), ('mazhiyong',), ('mazhiyong4',), ('meijianwei',), ('meilin',), ('meilu',), ('mengguanhua',),
        ('mengguanhua4',), ('mengzhaoying',), ('menqian',), ('menqian4',), ('miaohailan',), ('minduo',), ('mjliyun',),
        ('moujun2',), ('moukun',), ('mouminkang',), ('mouwenjun',), ('mouxinbing',), ('nanguili',), ('nanyinglan',),
        ('niechengling',), ('ningchao',), ('ningyong',), ('nxwushan',), ('ouguangling',), ('ouyangyao',),
        ('pangdefeng',),
        ('pangtieshi',), ('pangxiaodan',), ('pangxiaodan4',), ('panleyun',), ('panqian',), ('panwentong',),
        ('panyang',),
        ('panyuanju',), ('panyuanju4',), ('panyunhong',), ('panzhe',), ('panzhian',), ('panzhigang',), ('peijianfeng',),
        ('peizheng',), ('peizhidan',), ('pengcijun',), ('penghongying',), ('pengjiandong',), ('pengjincheng',),
        ('pengjing',), ('penglujuan',), ('pengshanhai',), ('pengshanhai4',), ('pengshengcheng',), ('pengsuiren',),
        ('pengtao',), ('pengtao2',), ('pengweidan',), ('pengweidan4',), ('pengxizhang',), ('pengxuxuan',),
        ('pengying2',),
        ('pengyong',), ('pubing',), ('pubing4',), ('puliang',), ('puliang4',), ('puxizhong',), ('puyuanqiang',),
        ('puyubi',), ('qh',), ('qianchangming',), ('qiangyuanbo',), ('qiaoxiaoqing',), ('qiboying',), ('qilanlan',),
        ('qindong',), ('qindongmei',), ('qinkunsheng',), ('qinkunsheng2',), ('qinqin',), ('qinshiwei',),
        ('qinxiandong',),
        ('qinxiaohua',), ('qinxudong',), ('qinyanfeng',), ('qinyouzhong',), ('qiqingjie',), ('qiuganglin',),
        ('qiuguiling',), ('qiuwensheng',), ('qiuyi',), ('qiuyu',), ('qiuzhicheng',), ('quandayong',), ('quannana',),
        ('quannana2',), ('quanzhongrong',), ('quping',), ('quping4',), ('ranlongsheng',), ('ranmengnian',),
        ('ranqishan',),
        ('ranzehui',), ('raolei',), ('raoqianquan',), ('raoqianquan3',), ('raoqianquan4',), ('renhuaichaoyang',),
        ('renhui',), ('renjun',), ('renshiying',), ('rensongying',), ('rlm',), ('shangyanglu',), ('shanhuiying',),
        ('shence',), ('shenghongzheng',), ('shengjieting',), ('shenjing',), ('shenmaoji',), ('shenmingming',),
        ('shenmingming4',), ('shenrong',), ('shibinghua',), ('shiguoqing',), ('shilei',), ('shilifen',), ('shitianyu',),
        ('shixiangya',), ('shongzhenning',), ('shuaixianteng',), ('shufeng',), ('siliuxia',), ('siliuxia2',),
        ('songlei',),
        ('songlianju',), ('songling',), ('songpujiao',), ('songqinwu',), ('songshuguang',), ('songxiurong',),
        ('songying',),
        ('suchangshan',), ('sucunqing',), ('sudaobing',), ('sugang',), ('suishiyu',), ('sujun',), ('sunbaozhen',),
        ('sungang2',), ('sunguoan',), ('sunhua',), ('sunhua4',), ('sunjin',), ('sunjinbing',), ('sunnana',),
        ('sunqian',),
        ('sunsuhong',), ('sunxiaoxian',), ('sunxingshan',), ('sunxingshan4',), ('sunzheng',), ('sunzheng4',),
        ('suping',),
        ('suwen',), ('suwen4',), ('suyun',), ('suzhigang',), ('suzhiyuan',), ('tanchangfu',), ('tanchangfu4',),
        ('tangaihua',), ('tangdan',), ('tangfengbi',), ('tanggang',), ('tanghaijun',), ('tanghaijun4',), ('tanghong',),
        ('tanghong4',), ('tanghongmei',), ('tangjing',), ('tangjing1',), ('tangjing4',), ('tanglu',), ('tangmingxiu',),
        ('tangwei',), ('tangweixing',), ('tangweixing4',), ('tangwentai',), ('tangxiaomei',), ('tangxingqin',),
        ('tangyangchun',), ('tangyangchun4',), ('tangyijun',), ('tangyongjiang2',), ('tangyulan',), ('tanhanjun',),
        ('tanqinrui',), ('tanwei',), ('tanxianjian',), ('tanxianjian2',), ('tanxiaofang',), ('tanxiaoqing',),
        ('tanxiaoqing4',), ('tanyuanjie',), ('tanyunyong',), ('tanzhouke',), ('taoxiuqing',), ('tianfeng',),
        ('tianjun',),
        ('tianmaoqiang',), ('tianmei',), ('tianxu',), ('tongguizhi',), ('tuyongxi',), ('wangbaoshu',), ('wangbolin',),
        ('wangchen',), ('wangchengshun',), ('wangchun',), ('wangenxue',), ('wangfan',), ('wangfengjie',),
        ('wanggenrong',),
        ('wangguoliang',), ('wangguoliang4',), ('wanghong',), ('wanghongxia',), ('wangjian2',), ('wangjianfeng',),
        ('wangjianhui',), ('wangjianping',), ('wangjianxia',), ('wangjianying',), ('wangjiao1',), ('wangjiao4',),
        ('wangjie1',), ('wangjin',), ('wangjin4',), ('wangjing',), ('wangjing1',), ('wangjing2',), ('wangjinyan',),
        ('wangjinyan2',), ('wangjunjie',), ('wangkunming',), ('wanglianfen',), ('wangling',), ('wangling1',),
        ('wangling2',), ('wanglirong',), ('wangmingquan',), ('wangmingxin',), ('wangqin',), ('wangqin4',),
        ('wangqizhao',),
        ('wangrenhe',), ('wangron',), ('wangruijun',), ('wangshan',), ('wangshan4',), ('wangshaojun',),
        ('wangshaomin',),
        ('wangshifei',), ('wangshigun',), ('wangshihai2',), ('wangshuai',), ('wangshuchun',), ('wangshuiwang',),
        ('wangsulai',), ('wangsuzhen',), ('wangtingqiang',), ('wangwei2',), ('wangwenchun',), ('wangwenchun4',),
        ('wangxiaodong',), ('wangxinying',), ('wangxiujuan',), ('wangxiuliang',), ('wangxiuquan',), ('wangxiyou',),
        ('wangxuan',), ('wangxuekai',), ('wangyajie',), ('wangyan',), ('wangyanhui',), ('wangyanhui2',), ('wangying1',),
        ('wangyinqi',), ('wangyong2',), ('wangyongfa',), ('wangyu',), ('wangyuanhong',), ('wangyuanjun',),
        ('wangyuanlan',),
        ('wangyuanyuan',), ('wangyuyu',), ('wangzengzhen',), ('wangzhangzhi',), ('wangzhen',), ('wangzhengguo',),
        ('wangzhiwen',), ('wangzhiwen4',), ('wangzhuanping',), ('wanjisheng',), ('wankaiqing',), ('wanming',),
        ('wanxiaoshuo',), ('wanxiaoshuo4',), ('weijianbo',), ('weilihua',), ('weixiang',), ('weixiaoya',), ('weixing',),
        ('weiyijiao',), ('weiyuqun',), ('wengyuhong',), ('wenjinwu',), ('wenkunming',), ('wenqi',), ('wenqi2',),
        ('wenshuyi',), ('wenwu',), ('wenxuanlan',), ('wenyanan',), ('wenzhaoxian',), ('wj3',), ('wliutao',), ('ws',),
        ('wuchengrong',), ('wufang1',), ('wufang4',), ('wugang',), ('wugang2',), ('wuguihua',), ('wuguilan',),
        ('wuguiyong',), ('wuhaili',), ('wuhaili4',), ('wuhaitao',), ('wuhongyun',), ('wuju',), ('wujun2',), ('wukai',),
        ('wuke',), ('wukuping',), ('wulei',), ('wulei2',), ('wumin4',), ('wumingbo',), ('wuping2',), ('wuqinzhen',),
        ('wusamuga',), ('wushan3',), ('wushan4',), ('wushuhong',), ('wutianming',), ('wutianxiang',), ('wuwenqiang',),
        ('wuxianbing',), ('wuxianbing4',), ('wuxinglong',), ('wuxingqiang',), ('wuxuegang',), ('wuxuenong',),
        ('wuxuenong3',), ('wuxuenong4',), ('wuxueyan',), ('wuxuezhen',), ('wuxuezhen4',), ('wuyang',), ('wuyanhe',),
        ('wuyibin',), ('wuyifang',), ('wuyong',), ('wuyong1',), ('wuyong4',), ('wuzelan',), ('wuzheng',), ('wwzcl',),
        ('wwzjy',), ('wwzlijun',), ('wwzliuqiang',), ('wwzliurui',), ('wwzliuyang',), ('wwzlmj',), ('wwzlq',),
        ('wwzwumin',), ('wwzyc',), ('wwzyj',), ('wwzzb',), ('wy',), ('xdzhangjing',), ('xiacuilan',), ('xiadongfen',),
        ('xiangbin4',), ('xiangfasong',), ('xianglihua',), ('xiangqiurong',), ('xiangyanfei',), ('xiangyuxin',),
        ('xianjianhua',), ('xianjianhua4',), ('xiaodaipin',), ('xiaoguimei',), ('xiaoshiyong',), ('xiaoshiyong4',),
        ('xiaoshunwu',), ('xiaowanping',), ('xiaoxin',), ('xiaoxinghui',), ('xiaoxinghui2',), ('xiaoxue',),
        ('xiaoyao',),
        ('xiaozhanpeng',), ('xiaping',), ('xiaping4',), ('xiayu',), ('xiebing',), ('xiecaidi',), ('xiechengying',),
        ('xiechuanbo',), ('xiechuanbo2',), ('xiegengxiu',), ('xiejun',), ('xieming',), ('xietianhong',),
        ('xiexingyao',),
        ('xiexinxing',), ('xieyong',), ('xieyong2',), ('xieyuqiong',), ('xieziling',), ('xinren',), ('xinren4',),
        ('xiongcaijun',), ('xiongcan',), ('xiongchan',), ('xiongliangzhong',), ('xiongmin',), ('xiongxin',),
        ('xiongyuancheng',), ('xiyuming',), ('xizhijie',), ('xncc',), ('xncdd',), ('xncff',), ('xnchangchun',),
        ('xncwr',),
        ('xndh',), ('xndl',), ('xndzx',), ('xnfkr',), ('xnfy',), ('xngy',), ('xnhanchunhong',), ('xnhlh',), ('xnhxh',),
        ('xnkxk',), ('xnlah',), ('xnlcq',), ('xnlh',), ('xnlhm',), ('xnlkw',), ('xnlll',), ('xnlongyao',), ('xnlse',),
        ('xnlsl',), ('xnlt',), ('xnlxj',), ('xnlz',), ('xnmgh',), ('xnmq',), ('xnmxd',), ('xnmyh',), ('xnpsh',),
        ('xnrqq',),
        ('xnsh',), ('xnsw',), ('xnsxs',), ('xnwf',), ('xnwj',), ('xnwxb',), ('xnwxn',), ('xnwxz',), ('xnwy',),
        ('xnwzw',),
        ('xnxl',), ('xnxr',), ('xnxy',), ('xnxyt',), ('xnyangzhiyong',), ('xnysk',), ('xnywj',), ('xnyzy',), ('xnzcj',),
        ('xnzhc',), ('xnzj',), ('xnzjs',), ('xnzkc',), ('xnzl',), ('xnzsy',), ('xnzx',), ('xnzxc',), ('xnzxf',),
        ('xnzxx',),
        ('xnzzj',), ('xubaogang',), ('xuchunmei',), ('xudan',), ('xudawen',), ('xudianming',), ('xuebaosheng',),
        ('xuerui',), ('xuhaibo',), ('xuhaiyan1',), ('xuhuanxue',), ('xujia',), ('xujian',), ('xujian1',),
        ('xujingping',),
        ('xujun',), ('xuli',), ('xuli4',), ('xunying',), ('xurubo',), ('xushudong',), ('xushumin',), ('xuxianglin',),
        ('xuxiaoqin2',), ('xuxin',), ('xuxin2',), ('xuyi',), ('xuying4',), ('xuyongtao',), ('xuyongtao4',),
        ('xuyujie',),
        ('xuyulong',), ('xuzongzhao',), ('xy',), ('yalikesi',), ('yangbin1',), ('yangbin4',), ('yangcangliang',),
        ('yangchangbi',), ('yangchangke',), ('yangchao',), ('yangchuanmao',), ('yangchuanmao2',), ('yangchuanmao4',),
        ('yanggaoqiao',), ('yangguiyu',), ('yanghaiying',), ('yanghexia',), ('yanghong',), ('yanghui',),
        ('yangjiaqing',),
        ('yangjiwen',), ('yangjufang',), ('yangkai',), ('yanglili',), ('yangliu2',), ('yanglizhou',), ('yangmingjie',),
        ('yangpan',), ('yangqing',), ('yangqing2',), ('yangqingtao',), ('yangquanxing',), ('yangrui',), ('yangrui4',),
        ('yangshenlong',), ('yangshuwen',), ('yangsu',), ('yangtinghui',), ('yangwenjie',), ('yangwenjie4',),
        ('yangwenyou',), ('yangxia',), ('yangxiaohong',), ('yangxiaoyan2',), ('yangxingyan',), ('yangxiyuan',),
        ('yangxu',),
        ('yangxuefei',), ('yangxuefeng',), ('yangxuezhong',), ('yangyawei',), ('yangyibin',), ('yangying',),
        ('yangyingpo',), ('yangyongfu',), ('yangzhencai',), ('yangzhengying',), ('yangzhengying3',),
        ('yangzhengying4',),
        ('yangzhigang',), ('yangzhigang4',), ('yangzhiyong',), ('yangzhiyong4',), ('yanjun',), ('yankekun',),
        ('yanmin',),
        ('yanshilong',), ('yanwen',), ('yanxia',), ('yanxiaoyong',), ('yanxiaozheng',), ('yanxiong',), ('yanxuefeng',),
        ('yanyunlu',), ('yaobin',), ('yaomaoqiu',), ('yaoshengtao',), ('yechunsheng',), ('yefangyao',), ('yekexing',),
        ('yeyuhua',), ('yichunyan',), ('yijingcheng',), ('yinxinming',), ('yizusheng4',), ('ymhehongjun',),
        ('yongguoping',), ('yongguoping4',), ('youchunyue',), ('youmin',), ('youshaomo',), ('yuanhanmei',),
        ('yuanhuili',),
        ('yuanjianping',), ('yuanpeiguo',), ('yuanwei',), ('yuanwen',), ('yuanxifu',), ('yuanyuxian',), ('yuanzihan',),
        ('yudegang',), ('yuesuping',), ('yuexiaochun',), ('yufan',), ('yufeng',), ('yuguangming',), ('yuhong',),
        ('yuji',),
        ('yujiangxia',), ('yujingxuan',), ('yulijie',), ('yumaoquan',), ('yuqing',), ('yuqinghua',), ('yushanshan',),
        ('yushaohong',), ('yushousheng',), ('yusouku4',), ('yusuoku',), ('yutonggang',), ('yuwenjie',), ('yuwenlan',),
        ('yuxiaoqun',), ('yuxiumin',), ('yuyao',), ('yuyi',), ('yzs',), ('zengfeng',), ('zengshuhan',),
        ('zengxiaobin2',),
        ('zengzhu',), ('zengzhu2',), ('zhaiyijun',), ('zhangaiyu',), ('zhangbaoli',), ('zhangbihong',),
        ('zhangchunhui',),
        ('zhangchunlin',), ('zhangdebing',), ('zhangdeqiong',), ('zhangdonglian',), ('zhanggengjian',),
        ('zhangguanfeng',),
        ('zhangguanghui',), ('zhangguiping',), ('zhangguiqin',), ('zhanghaixia',), ('zhanghong',), ('zhanghongwei',),
        ('zhanghongxia',), ('zhanghongxia4',), ('zhanghua',), ('zhanghuali',), ('zhangjiacai',), ('zhangjiao',),
        ('zhangjiayu',), ('zhangjining',), ('zhangjun2',), ('zhangjun4',), ('zhangjunshang',), ('zhangjunshang4',),
        ('zhangkuncheng',), ('zhangkuncheng4',), ('zhanglifei',), ('zhangming',), ('zhangmingxing1',),
        ('zhangmingxing2',),
        ('zhangmingyuan',), ('zhangping',), ('zhangqiang2',), ('zhangqiong',), ('zhangqizhong',), ('zhangquanlu',),
        ('zhangrongzhao',), ('zhangshengbo',), ('zhangshengbo4',), ('zhangtianjiu',), ('zhangwei1',), ('zhangwei4',),
        ('zhangweimin',), ('zhangwenhui',), ('zhangwenshan',), ('zhangxianju',), ('zhangxianli',), ('zhangxiaochun',),
        ('zhangxiaochun4',), ('zhangxiaofeng',), ('zhangxiaofeng4',), ('zhangxiaoyan1',), ('zhangxiaoyan2',),
        ('zhangxieming',), ('zhangxin',), ('zhangxin4',), ('zhangxinchun',), ('zhangxing',), ('zhangxingyuan',),
        ('zhangxuejun',), ('zhangxuemei',), ('zhangxuemei4',), ('zhangxuxia',), ('zhangxuxia4',), ('zhangyanping4',),
        ('zhangyinbo',), ('zhangyong',), ('zhangyonghong2',), ('zhangyongqing',), ('zhangyongxiang',), ('zhangyuanyi',),
        ('zhangyuanyi4',), ('zhangyuhong',), ('zhangzhaoping',), ('zhangzhengbo',), ('zhangzhibin',), ('zhangzhibin2',),
        ('zhangzhiguo',), ('zhangzhijun',), ('zhangzhijun4',), ('zhangzhiyu',), ('zhangzhong',), ('zhangzhuangqing',),
        ('zhangzulong',), ('zhanhongliang',), ('zhaobo',), ('zhaodihua',), ('zhaohelian',), ('zhaohualiang',),
        ('zhaohualin',), ('zhaohuayu',), ('zhaojing1',), ('zhaojinzhi',), ('zhaolifeng',), ('zhaolijin',),
        ('zhaomeng',),
        ('zhaoping',), ('zhaowanxin',), ('zhaowei2',), ('zhaowei3',), ('zhaoxiao',), ('zhaoxuya',), ('zhaoyingju',),
        ('zhaoyongcong',), ('zhaoyu',), ('zhaozhiguo',), ('zhengchangquan',), ('zhenghaiying',), ('zhenghongchang',),
        ('zhenghongchang4',), ('zhengjinrong',), ('zhengnanguo',), ('zhengsujun',), ('zhengweijie',), ('zhengxianhua',),
        ('zhengxiaosen',), ('zhengxingbin',), ('zhengxinglan',), ('zhengyalin',), ('zhengyalin2',), ('zhengyungang',),
        ('zhengzebing',), ('zhongchangming',), ('zhonghao',), ('zhonghao2',), ('zhongjinyan',), ('zhongpeijun',),
        ('zhongshengbing',), ('zhongwei',), ('zhoubin2',), ('zhoubing',), ('zhouchenghua',), ('zhouchengjin',),
        ('zhouchengjin3',), ('zhouchengjin4',), ('zhoufengwu',), ('zhougang',), ('zhouhang',), ('zhouhong',),
        ('zhouhong2',), ('zhouhongyan',), ('zhouhui',), ('zhoujian',), ('zhoujianping',), ('zhoujingcai',),
        ('zhoujingcai2',), ('zhoujuan',), ('zhouleng',), ('zhouli3',), ('zhoulihe',), ('zhoushanshan',),
        ('zhoushanshan2',),
        ('zhoushaohua',), ('zhoushasha',), ('zhoushuang1',), ('zhoushuang2',), ('zhoushuqiong',), ('zhouxiaoli',),
        ('zhouxiaoli4',), ('zhouxiaolong',), ('zhouxinren',), ('zhouyanwen',), ('zhouyuanbo',), ('zhouzhijie',),
        ('zhuailan',), ('zhuchunling',), ('zhuchunping',), ('zhuchunping2',), ('zhudaojian',), ('zhugui',),
        ('zhugui4',),
        ('zhuhanwei',), ('zhuhongji',), ('zhuhongjiu',), ('zhuhua',), ('zhuhuanian',), ('zhulei',), ('zhulei4',),
        ('zhuohongping',), ('zhupingfan',), ('zhuxianyun',), ('zhuyan2',), ('zhuyan4',), ('zhuyao',), ('zhuyao4',),
        ('zhuyoutang',), ('zhuzhihong',), ('zouhaiyang',), ('zouliping',), ('zouliping4',), ('zouxuekun',), ('zouyun',),
        ('zuoshiyan',), ('zuoshiyan4',), ('zuoxiuhong',), ('zx',), ('zychenxiaohong',), ('zycl',), ('zygaoyuan',),
        ('zyliangli',), ('zyliuli',), ('zylixun',), ('zyliyi',), ('zyluoli',), ('zylw',), ('zyp',), ('zysr',),
        ('zywangfeng',), ('zywanggang',), ('zywanghong',), ('zywangxin',), ('zyyanghua',), ('zyyangjin',),
        ('zyyangli',),
        ('zyyangying',), ('zyzhaopeng',), ('zyzhaoyong',), ('zyzhengyi',))
    return ret1